### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ejwaibel** [nickclaw/atom-grunt-runner#35] opened 2015-02-23 17:51 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
TaskListView.attach (/Users/bztv56/.atom/packages/grunt-runner/lib/task-list-view.coffee:59:13)
```

**Comment by nickclaw** [comment] 2015-02-24 21:53
Duplicate of #34 
Thanks.

**Closed by nickclaw** 2015-02-24 21:53 UTC
