### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by superandrew** [nickclaw/atom-grunt-runner#56] opened 2015-05-20 12:46 UTC
[Enter steps to reproduce below:]

1. Open Package config

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.3
**Thrown From**: [grunt-runner](https://github.com/nickclaw/atom-grunt-runner) package, v0.9.1

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Users/superandrew/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:70

ReferenceError: path is not defined
  at ResultsView.module.exports.ResultsView.parseGruntFile (/Users/superandrew/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:70:44)
  at /Users/superandrew/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:42:47
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:274:29)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:37:32)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -1:29.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  6x -1:21.2.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -1:19.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:18.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:51.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:49.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "grunt-runner"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-jshint, v1.5.0
jsformat, v0.8.1
react, v0.11.8
terminal-panel, v1.14.1
terminal-status, v1.6.7

# Dev
No dev packages
```

**Comment by kokarn** [comment] 2015-05-20 12:53
This is a duplicate of #54 and fixed in master from https://github.com/nickclaw/atom-grunt-runner/commit/f70872d843affd71e3b2dd2c23d60b1291bdd431. 
Just waiting for @nickclaw to publish.

In the meantime you can download the package from here ( you only need to replace lib/grunt-runner-view.coffee ).

**Closed by kokarn** 2015-05-20 12:53 UTC

**Comment by nickclaw** [comment] 2015-05-21 19:04
Published!
