### ISSUE TITLE
Error loading Gruntfile: gruntfile not found

### ISSUE THREAD

**Issue by kudlajz** [nickclaw/atom-grunt-runner#71] opened 2015-10-30 09:09 UTC
I am getting a following error:
![screen shot 2015-10-30 at 10 06 26](https://cloud.githubusercontent.com/assets/4209081/10841936/07ff06a8-7eee-11e5-90ab-89a1445c75c5.png)
but gruntfile.js is in my root folder..
![screen shot 2015-10-30 at 10 06 31](https://cloud.githubusercontent.com/assets/4209081/10841937/081c17fc-7eee-11e5-8f62-ef583b77b5be.png)
I have tried Window: reload, opening my folder directly, via Project Manager, renaming gruntfile.js to Gruntfile.js, but nothing helped.

Settings:
![screen shot 2015-10-30 at 10 09 27](https://cloud.githubusercontent.com/assets/4209081/10841969/56834aaa-7eee-11e5-9eec-76d476314c2e.png)

I am using OS X 10.11.

**Comment by kokarn** [comment] 2015-10-31 14:55
Duplicate of either #20 or #25

**Closed by kokarn** 2015-10-31 14:55 UTC
